name: expense_tracker
description: "A Flutter expense tracker with Firebase authentication, Firestore storage, insights, and premium feature simulation."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  intl: ^0.18.1         # For date formatting
  fluttertoast: ^8.2.4  # Toast notifications

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.6

  # State management
  provider: ^6.1.1

  # Unique ID generation
  uuid: ^3.0.7

  # Charts & Insights
  fl_chart: ^0.66.0

  # Local storage (optional, for caching)
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # Uncomment when you add images or icons
  # assets:
  #   - assets/images/
