name: expense_tracker
description: "A Flutter expense tracker with Firebase authentication, Firestore storage, insights, and premium feature simulation."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.9.1  # ✅ added for icons

  # Firebase (compatible with Flutter 3.8.x)
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0

  # State management
  provider: ^6.1.2

  # Unique ID generation
  uuid: ^4.5.1

  # Charts & Insights
  fl_chart: ^1.1.0   # ✅ downgraded to supported version

  # Local storage (optional, for caching)
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # Uncomment when you add images or icons
  # assets:
  #   - assets/images/

dependency_overrides:
  web: ^1.0.0
