// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtXOIK0Q-tfgwiJJdATezSGlzhs2sPDOs',
    appId: '1:439862400348:web:95257ea7dad8d13c5f1d99',
    messagingSenderId: '439862400348',
    projectId: 'expense-tracker-8ab00',
    authDomain: 'expense-tracker-8ab00.firebaseapp.com',
    storageBucket: 'expense-tracker-8ab00.firebasestorage.app',
    measurementId: 'G-2X8GX77FB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ1w4bEsTBY6Zyfmbde7-lj7LgDPHCiRA',
    appId: '1:439862400348:android:1fa82702bfe7e2b15f1d99',
    messagingSenderId: '439862400348',
    projectId: 'expense-tracker-8ab00',
    storageBucket: 'expense-tracker-8ab00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAHe1mCSCRaClgGvx2iFZBGpgbC3F6qjc',
    appId: '1:439862400348:ios:b532575585e5529e5f1d99',
    messagingSenderId: '439862400348',
    projectId: 'expense-tracker-8ab00',
    storageBucket: 'expense-tracker-8ab00.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAHe1mCSCRaClgGvx2iFZBGpgbC3F6qjc',
    appId: '1:439862400348:ios:b532575585e5529e5f1d99',
    messagingSenderId: '439862400348',
    projectId: 'expense-tracker-8ab00',
    storageBucket: 'expense-tracker-8ab00.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtXOIK0Q-tfgwiJJdATezSGlzhs2sPDOs',
    appId: '1:439862400348:web:e7c2f62029648df65f1d99',
    messagingSenderId: '439862400348',
    projectId: 'expense-tracker-8ab00',
    authDomain: 'expense-tracker-8ab00.firebaseapp.com',
    storageBucket: 'expense-tracker-8ab00.firebasestorage.app',
    measurementId: 'G-ELDVPWKK1X',
  );
}
