// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG8bFAI4IiVFoxvnSVt7NKA36gWqUk4bU',
    appId: '1:757226546874:web:7f7bb7de766f4c47aac483',
    messagingSenderId: '757226546874',
    projectId: 'expensetracker-94618',
    authDomain: 'expensetracker-94618.firebaseapp.com',
    storageBucket: 'expensetracker-94618.firebasestorage.app',
    measurementId: 'G-8YFH4RCH8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh2L4nE1FYHqjnkP_O7WHZf5VsykEMu1Q',
    appId: '1:757226546874:android:d3b9a1c3b8d1ae0eaac483',
    messagingSenderId: '757226546874',
    projectId: 'expensetracker-94618',
    storageBucket: 'expensetracker-94618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBHVz9G7jl3zCZdTi5WCFQNe7RFOD139Y',
    appId: '1:757226546874:ios:fbecd71f39ac3bcfaac483',
    messagingSenderId: '757226546874',
    projectId: 'expensetracker-94618',
    storageBucket: 'expensetracker-94618.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBHVz9G7jl3zCZdTi5WCFQNe7RFOD139Y',
    appId: '1:757226546874:ios:fbecd71f39ac3bcfaac483',
    messagingSenderId: '757226546874',
    projectId: 'expensetracker-94618',
    storageBucket: 'expensetracker-94618.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG8bFAI4IiVFoxvnSVt7NKA36gWqUk4bU',
    appId: '1:757226546874:web:e7aeb6fdc78c0d3caac483',
    messagingSenderId: '757226546874',
    projectId: 'expensetracker-94618',
    authDomain: 'expensetracker-94618.firebaseapp.com',
    storageBucket: 'expensetracker-94618.firebasestorage.app',
    measurementId: 'G-41Z64SXPYL',
  );
}
